version: '3.6'
services:
    vosint-event:
        image: vienai/vosint-backendevent:1.0.2
        ports: 
            - 9101:6101             
        environment:
            - ENVIRONMENT=PRODUCTION
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong2.vosint.edu.vn:60002,mong3.vosint.edu.vn:60003/admin?replicaSet=replicaVosint&authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - PIPELINE_API=http://vosint-pipeline-master:6101
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master1:9200,http://master2:9200
            - EXTRACT_API=http://vosint-eventextraction:1510/extract
        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1      
            placement:
                constraints:
                    - node.hostname==aivn  
        networks:
            - vosint3_system_network

networks: 
  vosint3_system_network:
    external: true

